# -*- coding: utf-8 -*-
""" 
Build a Crypto Trading Algorithm With a Neural Network

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TRzqYfLdarN9hzziOYuWhaF9m9tbEIPu

**Install Dependencies**
"""


"""**Import dependencies**"""

import os
import pandas as pd
import yfinance as yf
import alpaca as tradeapi
import alpaca_trade_api as tradeapi
import configparser
import pytz
import locale
import pandas_market_calendars as mcal

from alpaca_trade_api.rest import REST, TimeFrame, APIError
import alpaca_trade_api as alpaca
from ta.volatility import BollingerBands
from ta.momentum import RSIIndicator
from ta.trend import sma_indicator
from tqdm import tqdm
from requests_html import HTMLSession
from datetime import datetime
from slack import WebClient
from slack.errors import SlackApiError
import time
from alpaca.data.historical import CryptoHistoricalDataClient
from alpaca.data.requests import CryptoBarsRequest
from alpaca.data.timeframe import TimeFrame
from alpaca.trading.client import TradingClient
from alpaca.trading.requests import MarketOrderRequest
from alpaca.trading.enums import OrderSide, TimeInForce
from datetime import datetime
from dateutil.relativedelta import relativedelta
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dense, Dropout, LSTM
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error
import json
import logging
#import config
import asyncio
from lumibot.brokers import Alpaca
from lumibot.backtesting import YahooDataBacktesting
from lumibot.strategies.strategy import Strategy
from lumibot.traders import Trader
from datetime import datetime
from alpaca_trade_api import REST
#from timedelta import Timedelta
time.sleep(1)
from google.colab import drive
drive.mount('/content/drive')


"""**Build a Crypto Trading Algorithm With a Neural Network**

In the context of crypto trading, an ANN functions as a trader continuously monitoring asset prices 24/7, adapting trading positions based on historical and live data, among other metrics.

ANNs can be employed for **predictive analysis and decision-making** in executing crypto trades. They analyze historical market data, identify patterns, and adjust trading strategies based on evolving market conditions.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import requests
from datetime import datetime, timedelta
import tensorflow.python.tools
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from sklearn.preprocessing import StandardScaler

"""**Import data from GeckoTerminal DEX API, Create the ANN Model, Train the ANN with Crypto Price Data, Make Predictions, and Visualize the Returns**"""

# Import data from GeckoTerminal DEX API

network = 'eth'
pool_address = '' #DAI-WETH Pool
parameters = f'{network}/pools/{pool_address}'
specificity = f'{1}'

#URL with your specifications
url = f'https://api.geckoterminal.com/api/v2/networks/{parameters}/ohlcv/day?aggregate={specificity}'
response = requests.get(url)
data = response.json()

#Turning into pandas dataframe, turning the date value into datetime format,
# making it the index

data = data['data']['attributes']['ohlcv_list']
df = pd.DataFrame(data, columns=['Date', 'Open', 'Close', 'High', 'Low', 'Volume'])
df['Date'] = pd.to_datetime(df['Date'], unit = 's')
df.set_index('Date', inplace = True)

# Creating ANN Model

layer_builder = Sequential()
# Adding Layers - We will now proceed with creating our linear stack of layers.
# First input layer
layer_builder.add(Dense(units = 128, kernel_initializer = 'uniform',
                        activation = 'relu', input_dim = X.shape[1]))
# Second input layer
layer_builder.add(Dense(units = 128, kernel_initializer = 'uniform',
                        activation = 'relu'))
# Output layer
layer_builder.add(Dense(units = 1, kernel_initializer = 'uniform',
                        activation = 'sigmoid'))

## Training the ANN with Crypto Price Data
# We will need to train our ANN in order to build our crypto algorithmic trading
# strategy. We’ll employ the following 3 basic technical analysis techniques
# to train our ANN:
# 3-month moving average (3MA)
# 10-month moving average (10MA)
# 15-month moving average (15MA)

# Clean up and standardize data
df['3MA'] = df['Close'].shift(1).rolling(window = 3).mean()
df['10MA'] = df['Close'].shift(1).rolling(window = 10).mean()
df['15MA'] = df['Close'].shift(1).rolling(window = 15).mean()
df['Price_Rise'] = np.where(df['Close'].shift(-1) > df['Close'], 1, 0)
df = df.dropna()
X = df.iloc[:, 5:-1]
Y = df.iloc[:, -1]

# Split up our X and Y Data

# The objective here is to split up our X data (i.e. 3MA, 10MA, and 15MA columns)
# and the Y dataset (i.e. price rise or fall) into training and testing sets.
# The training set is used to arrive at the adjusted weights through
# backpropagation, while the test set is used to see how the model would perform
# on newly instituted data, which is our backtest.
# After using the test data set, we will employ several metrics to determine
# the efficiency of our model.

#Create X_train, X_test, Y_train, Y_test

split_data = int(len(df)*0.7)
X_train, X_test, Y_train, Y_test = X.iloc[:split_data, :], X.iloc[
    split_data:, :], Y.iloc[:split_data], Y.iloc[split_data:]

# Standardizing the Dataset

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Compile the layers

layer_builder.compile(optimizer = 'adam', loss = 'mean_squared_error',
                      metrics = ['accuracy'])

# #Fit ANN to training set
# We then fit our ANN to our training data, using a ‘batch size’ of 5, which
# is the number of data points used to compute the error before backpropagation,
# and 100 ‘epochs’, the number of times the training model will be used on the
# training set.

layer_builder.fit(X_train, Y_train, batch_size = 5, epochs = 100)
Y_pred = layer_builder.predict(X_test)
Y_pred = (Y_pred > 0.5)
#Store predictions back into dataframe
df['Y_Pred'] = np.NaN
df.iloc[(-len(Y_pred)):,-1:] = Y_pred.flatten()

# Visualizing the Returns

# Strategy Returns
df['Returns'] = 0
# Get the log returns
df['Returns'] = np.log(df['Close']/df['Close'].shift(1))
# Shift so that the returns are in line with the day they were achieved
df['Returns'] = df['Returns'].shift(-1)

df['Strategy Returns'] = 0
df['Strategy Returns'] = np.where(
    df['Y_Pred'] == True, df['Returns'], - df['Returns'])
df['Cumulative Market Returns'] = np.cumsum(df['Returns'])
df['Cumulative Strategy Returns'] = np.cumsum(df['Strategy Returns'])

# Visualize Returns
plt.figure(figsize=(12, 4))
plt.plot(
    df['Cumulative Strategy Returns'], color = 'Blue', label = 'Strategy Returns')
plt.plot(
    df['Cumulative Market Returns'], color = 'Green', label = 'Market Returns')
plt.xlabel('Date')
plt.xticks(df.index[::5], rotation = 45)
plt.ylabel('Log-Returns')
plt.legend()
plt.show()
